apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-staging
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - ipfs-node
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: do-block-storage
  local:
    path: /home/chris/ipfs/staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipfs-staging
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: do-block-storage
  selector: {}
