version: '3.8'
services:
  app:
    build:
      context: .
    command: node /home/node/app/index.js
    container_name: 'gridfire-server'
    depends_on:
      - rabbitmq
      - mongo
    networks:
      - internal
    ports:
      - 5000:5000
    restart: always
    tmpfs: /home/node/app/tmp
  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    image: mongo
    networks:
      internal:
        aliases:
          - mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - db-data:/data/db
  rabbitmq:
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    expose:
      - 5672
    hostname: rabbitmq
    image: rabbitmq:3.9.12-management
    networks:
      internal:
        aliases:
          - rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
  ipfs-host:
    container_name: ipfs-host
    image: ipfs/go-ipfs
    expose:
      - 5001
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - ipfs-data:/data/ipfs
      - ipfs-export:/export
    networks:
      internal:
        aliases:
          - ipfs-host
networks:
  internal:
    driver: bridge
volumes:
  db-data:
  ipfs-data:
  ipfs-export:
