apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-data
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - ipfs-node
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: hostpath
  local:
    path: /home/chris/ipfs/data
