apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-staging
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - ipfs-node
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /home/chris/ipfs/staging
