apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  GRIDFIRE_EDITIONS_ADDRESS: "0x80241623699c5815dA9e8EE9F6ff7f7009a95989"
  GRIDFIRE_PAYMENT_ADDRESS: "0x80241623699c5815dA9e8EE9F6ff7f7009a95989"
  DAI_CONTRACT_ADDRESS: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
  IPFS_NODE_HOST: http://ipfs-node.default.svc.cluster.local:5001
  NETWORK_URL: https://arb-mainnet.g.alchemy.com/v2
  NODE_ENV: production
  QUEUE_MESSAGE: message
  QUEUE_TRANSCODE: transcode
  TEMP_PATH: /tmp
