apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  CONTRACT_ADDRESS: "0x7Bc4F4FF48865aD87Ed0033359e0f2dcc537c1dF"
  DAI_CONTRACT_ADDRESS: "0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1"
  IPFS_NODE_HOST: http://ipfs-node.default.svc.cluster.local:5001
  NETWORK_URL: https://arb-mainnet.g.alchemy.com/v2
  NODE_ENV: production
  QUEUE_MESSAGE: message
  QUEUE_TRANSCODE: transcode
  TEMP_PATH: /tmp
